import handheldPhone from './handheldPhone.png'
import operate from './operate.png'
import driver from './drive.png'
import logo from './logo.png'
import location from './location.png'
import suvColorAches from './suv-ache.png'
import suvColorCream from './suv-cream.png'
import Elia from './Elia.jpeg'
import James from './James.jpeg'
import passenger from './Passenger.png'
import map from './map.png'
import ChargesBadge from './charges.png'
import opendoor from './openDoor.png'
import handShake from './handShake.png'
import bgSvg from './bg__svg.png'
import bgPath from './bg__parth.png'
import checked from './checked.png'
import experience from './experience.png'
import womanlearn from './technovixwoman.png'
import appLogo from './apple-logo.png'
import Mapping from './Mapping.png'
import iphones from './Iphones.png'
import appleStore from './appleStore.png'
import playStore from './playStore.png'
import playStoreLogo from './play-store-logo.png'
import paypal from './paypal.png'
import visa from './Visa.png'
import master from './Master.png'
import cash from './cash.png'
import angleRight from './angleRight.png'

export default {bgSvg,cash, angleRight, paypal, master, visa, playStoreLogo, appleStore, playStore, 
        womanlearn,iphones, appLogo, experience, checked, bgPath, handShake, opendoor, ChargesBadge, handheldPhone, operate, driver, logo, location, suvColorAches,map,
         suvColorCream, Elia, James, passenger, Mapping
    }