import handheldPhone from './handheldPhone.png'
import operate from './operate.png'
import driver from './driver.png'
import logo from './logo.png'
import location from './location.png'
import suvColorAches from './suv-ache.png'
import suvColorCream from './suv-cream.png'
import Elia from './Elia.png'
import James from './James.png'
import passenger from './Passenger.png'
import map from './map.png'
import ChargesBadge from './charges.png'
import iphone13 from './iPhone13Pro.png'
import iphone14 from './iPhone14Pro.png'
import opendoor from './openDoor.png'
import handShake from './handShake.png'
import bgSvg from './bg__svg.png'
import bgPath from './bg__parth.png'
import checked from './checked.png'
import experience from './experience.png'
import womanlearn from './technovixwoman.png'
import appLogo from './apple-logo.png'
import iphones from './Iphones.png'
import appleStore from './appleStore.png'
import playStore from './playStore.png'


export default {bgSvg, appleStore, playStore, womanlearn,iphones, appLogo, experience, checked, bgPath, handShake, opendoor, iphone13, iphone14, ChargesBadge, handheldPhone, operate, driver, logo, location, suvColorAches,map, suvColorCream, Elia, James, passenger }