export { Home } from './Home/Home'
export { default as InterP } from './InterP/InterP'
export { default as LocalP } from './LocalP/LocalP'
export { default as Login } from './Login/Login'
export { default as NotFound } from './NotFound/NotFound'
export { default as PassengerDB } from './PassengerDB/PassengerDB'
export { default as Profile } from './Profile/Profile'
export { default as User } from './User/User'
export { default as UserSignup} from './SignUp/SignUp'
export { default as Loginuser} from './Login/User/Login'
export { default as ForgetPwd} from './ForgetPwd/ForgetPwd'
export { default as OTP} from './OTP/OTP'
export { default as Newpwd} from './Newpwd/Newpwd'