export { default as Home } from './Home/Home'
export { default as InterP } from './InterP/InterP'
export { default as LocalP } from './LocalP/LocalP'
export { default as Login } from './Login/Login'
export { default as NotFound } from './NotFound/NotFound'
export { default as PassengerDB } from './PassengerDB/PassengerDB'
export { default as Profile } from './Profile/Profile'
export { default as User } from './User/User'