export { default as Dashboard } from './Dashboard/Dashboard'
export { default as Upcoming} from './Trip/Upcoming'
export { default as Booking } from './Booking/Booking'
export { default as Message } from './Messages/Messages'
export { default as PassengerProfile } from './Profile/Profile'
export { default as ProfileSetting } from './Profile/ProfileSetting/ProfileSetting'
export { default as PaymentSettings } from './PaymentSettings/PaymentSettings'
export { default as AddCard } from './AddCard/AddCard'
export { default as GetHelp } from './GetHelp/GetHelp'
export { default as Trip } from './Dashboard/Trip'
