export { default as FleetProfile } from "./Profile/Profile";
export { default as FleetDriver } from "./FleetDriver/FleetDriver";
export { default as OrderHistory } from "./OrderHistory/OrderHistory";
// export { default as FleetDriver } from "./FleetDriver/FleetDriver";
export { default as Vehicles } from "./Vehicles/Vehicles";
export { default as FleetInvoice } from "./Invoice/Invoice";
export { default as RiderInvoice } from "./RiderInvoice/RiderInvoice";
export { default as Compensation } from "./Compensation/Compensation";
export { default as DailyReport } from "./DailyReport/DailyReport";
export { default as WeeklyReport } from "./WeeklyReport/WeeklyReport";
export { default as FleetPayouts } from "./Payout/Payout";
export { default as FleetDashboard } from "./Dashboard/Dashboard";
export { default as Invoice } from "./Invoice/Invoice";
export { default as FleetSetting } from "./FleetSetting/FleetSetting.jsx";
