import { images } from "../asset";

export const trips = [
    {
        _id: 1,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 2,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 3,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 4,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 5,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 6,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    },
    {
        _id: 7,
        image: images.Elia,
        name: 'Christiana James',
        rating: 4.6,
        cost: 45.40,
        arrivalTime: '8:00AM',
        takeOffTime:  '7: 00Am',
        takeOffPlace: 'Plailly Villa',
        destination: 'CINEMA CGR',
        date: '12 September,2022',
    }
]