import { images } from "../asset";

export const trips = [
  {
    _id: 1,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa",
    destination: "CINEMA CGR",
    date: "12 September,2022",
    ride_status: "completed",
  },
  {
    _id: 2,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa",
    destination: "CINEMA CGR",
    date: "12 September,2022",
    ride_status: "upcoming",
  },
  {
    _id: 3,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa",
    destination: "CINEMA CGR",
    ride_status: "completed",
    date: "12 Febrary,2022",
  },
  {
    _id: 4,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa",
    destination: "CINEMA CGR",
    date: "22 march,2022",
    ride_status: "completed",
  },
  {
    _id: 5,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace:
      "Plailly Villa Plailly Villa Plailly Villa Plailly Villa Plailly Villa",
    destination: "CINEMA CGR",
    date: "04 April,2022",
    ride_status: "completed",
  },
  {
    _id: 6,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa",
    ride_status: "upcoming",
    destination: "CINEMA CGR",
    date: "12 June,2022",
  },
  {
    _id: 7,
    image: images.Elia,
    name: "Christiana James",
    rating: 4.6,
    cost: 45.4,
    arrivalTime: "8:00AM",
    takeOffTime: "7: 00Am",
    takeOffPlace: "Plailly Villa ",
    destination: "CINEMA CGR",
    ride_status: "upcoming",
    date: "11 May,2022",
  },
];
