export const videos = [
    {
        id: 1,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 2,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 3,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 4,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 5,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 6,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
    {
        id: 7,
        title: 'Info Session for new Driver-Partners',
        activities: '4',
        image: '',
        status: 'Not Start',
        progress: 70,
    },
];
